name: Build odysseyn1x

on:
  push:
    paths:
      - 'build.sh'
      - 'txt.txt'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build for amd64
      run: |
        sed -i "/Exit if user isn't root/aVERSION='$(cat version)'" build.sh
        sed -i "/Exit if user isn't root/aARCH='amd64'" build.sh
        sudo ./build.sh

    - name: Build for i686
      run: |
        sed -i "s/ARCH='amd64'/ARCH='i686'/g" build.sh
        sudo ./build.sh
